# Generated by Django 5.1.3 on 2024-11-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boatinstance',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
