# Generated by Django 5.1.3 on 2024-11-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0002_alter_boatinstance_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boatinstance',
            name='price_per_day',
        ),
        migrations.AddField(
            model_name='boatmodel',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10),
            preserve_default=False,
        ),
    ]
