# Generated by Django 5.1.3 on 2024-11-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='start_date',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='end_date',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='start_date',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
