# Generated by Django 5.1.3 on 2024-11-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_pago_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='payment_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
